[meta]
save_dir = "exp"
seed = 3407

[finetune]
finetune = true
ckpt_dir = "/root/code/github_repos/DiariZen/recipes/diar_ssl/exp/kaldi_merged_1219_all_ft_large/checkpoints/epoch_0016"

[trainer]
path = "trainer_dual_opt.Trainer"
[trainer.args]
max_epochs = 30
gradient_percentile = 90
gradient_history_size = 1000
save_max_score = false
save_ckpt_interval = 1
# 每 N 次 steps_trained 存 checkpoints/step_XXXXXXXX/；0=关闭
save_ckpt_every_n_steps = 5000
max_num_step_checkpoints = 10
max_patience = 10
max_num_checkpoints = 100
gradient_accumulation_steps = 2
validation_interval = 1
freeze_wavlm = false
lr_decay = false
use_one_cycle_lr = false

[optimizer_small]
path = "torch.optim.AdamW"
[optimizer_small.args]
lr = 5e-6

[optimizer_big]
path = "torch.optim.AdamW"
[optimizer_big.args]
lr = 2e-5

[model]
path = "diarizen.models.eend.model_wavlm_conformer.Model"
[model.args]
wavlm_src = "wavlm_large_s80_md"
wavlm_layer_num = 25
wavlm_feat_dim = 1024
attention_in = 256
ffn_hidden = 1024
num_head = 4
num_layer = 4
dropout = 0.1
chunk_size = 8
use_posi = false
output_activate_function = false
selected_channel = 0
max_speakers_per_chunk = 4
max_speakers_per_frame = 4

[train_dataset]
path = "dataset.DiarizationDataset"
[train_dataset.args]
scp_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/train/wav.scp"
rttm_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/train/rttm"
uem_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/train/all.uem"
chunk_size = 8
chunk_shift = 6
sample_rate = 16000
full_utterance = true
max_sessions = 0
max_chunks = 0

[train_dataset.dataloader]
batch_size = 10
num_workers = 16
prefetch_factor = 4
persistent_workers = true
drop_last = true
pin_memory = true

[validate_dataset]
path = "dataset.DiarizationDataset"
[validate_dataset.args]
scp_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/dev/wav.scp"
rttm_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/dev/rttm"
uem_file = "data/generated_samples_for_DiariZen_0317_longaudio_vad_label_all_ft_large/dev/all.uem"
chunk_size = 8
chunk_shift = 8
sample_rate = 16000
full_utterance = true
max_sessions = 0
max_chunks = 0

[validate_dataset.dataloader]
batch_size = 10
num_workers = 16
prefetch_factor = 4
persistent_workers = true
drop_last = true
pin_memory = true
